using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace Markov
{
    public class MarkovChain
    {
        private Dictionary<string, List<(int maxIndex, string unit)>> unitWeights = new Dictionary<string, List<(int maxIndex, string unit)>>();
        private string delineator;
        private int n;

        public MarkovChain(string Delineator, string DataPath, string Regex, int N = 2)
        {
            delineator = Delineator;
            n = N;
            CalculateWeights(DataPath, Regex);
        }

        //calculate the weights from the training data
        private void CalculateWeights(string dataPath, string regex)
        {
            List<string> units = new List<string>();
            string previousUnits = "";
            int acceptableRange = 0;
            int totalMaxIndex;
            bool hasAddedUnit;

            //retrieve all the units from the text using the regular expression
            using StreamReader reader = new StreamReader(dataPath);
            MatchCollection matches = Regex.Matches(reader.ReadToEnd(), regex);

            for (int i = 0; i < matches.Count; i++)
            {
                units.Add(matches[i].Value);
            }

            //go over all of the sets of n units in the unit list to add them to the weights list
            for (int i = 0; i < units.Count(); i++)
            {
                acceptableRange = Math.Min(n, i);
                previousUnits = ConcatenateUnits(units.GetRange(i - acceptableRange, acceptableRange));

                if (unitWeights.ContainsKey(previousUnits))
                {
                    hasAddedUnit = false;

                    for (int j = 0; j < unitWeights[previousUnits].Count(); j++)
                    {
                        if (unitWeights[previousUnits][j].unit == units[i])
                        {
                            unitWeights[previousUnits][j] = (unitWeights[previousUnits][j].maxIndex + 1, unitWeights[previousUnits][j].unit);
                            hasAddedUnit = true;
                            break;
                        }
                    }

                    if (!hasAddedUnit)
                    {
                        unitWeights[previousUnits].Add((1, units[i]));
                    }
                }
                else
                {
                    unitWeights.Add(previousUnits, new List<(int maxIndex, string unit)> { (1, units[i]) });
                }
            }

            //go over the list again after it's been filled up to increment the maxIndex values by all previous values
            foreach (KeyValuePair<string, List<(int maxIndex, string unit)>> keyval in unitWeights)
            {
                totalMaxIndex = 0;

                for (int i = 0; i < keyval.Value.Count(); i++)
                {
                    totalMaxIndex += keyval.Value[i].maxIndex;
                    unitWeights[keyval.Key][i] = (totalMaxIndex, keyval.Value[i].unit);
                }
            }
        }

        private string ConcatenateUnits(List<string> units)
        {
            if (units.Count() == 0)
            {
                return "";
            }

            string output = units[0];

            for (int i = 1; i < units.Count; i++)
            {
                output += " " + units[i];
            }

            return output;
        }

        //get the next unit based in a generated string
        public string GetNextUnit(string previousUnits)
        {
            //first, check if this set of previous units exists in the dictionary
            if (!unitWeights.ContainsKey(previousUnits))
            {
                return delineator;
            }

            //find the total weights (total prevalence) of all units
            List<(int maxIndex, string unit)> crudeResult = unitWeights[previousUnits];

            //then, retrieve the correct unit using a random int generated by multiplying Math.Rand by the total weight
            Random random = new Random();
            int randomInt = random.Next(crudeResult[crudeResult.Count() - 1].maxIndex + 1);

            //and finally, retrieve the first unit in the dictionary record with a maxIndex >= the generated random int
            for (int i = 0; i < crudeResult.Count(); i++)
            {
                if (crudeResult[i].maxIndex >= randomInt)
                {
                    return crudeResult[i].unit;
                }
            }

            return delineator;
        }

        //generate a string with a set number of units
        public string GenerateString(int lengthInUnits)
        {
            List<string> previousUnits = new List<string>();
            string output = "";

            //loop until the maximum number of units is reached
            for (int i = 0;i < lengthInUnits; i++)
            {
                previousUnits.Add(GetNextUnit(ConcatenateUnits(previousUnits)));
                output += previousUnits[previousUnits.Count - 1];

                if (previousUnits.Count > n)
                {
                    previousUnits.RemoveAt(0);
                }
            }

            return output;
        }
    }
}
